# Generated by Django 2.2.2 on 2020-09-20 10:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('default_value', models.CharField(max_length=255)),
                ('value_type', models.CharField(max_length=255)),
                ('edit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('dob', models.CharField(max_length=8)),
                ('level', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('activate', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PretrainedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facecheckin.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facecheckin.FaceImage'),
        ),
        migrations.CreateModel(
            name='CheckInTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.PositiveIntegerField()),
                ('end_time', models.PositiveIntegerField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facecheckin.Employee')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facecheckin.FaceImage')),
            ],
        ),
    ]
