# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faceWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FaceWindow(object):
    def setupUi(self, FaceWindow):
        FaceWindow.setObjectName("FaceWindow")
        FaceWindow.setEnabled(True)
        FaceWindow.resize(783, 581)
        FaceWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(FaceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.previous_bt = QtWidgets.QPushButton(self.centralwidget)
        self.previous_bt.setObjectName("previous_bt")
        self.gridLayout.addWidget(self.previous_bt, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.record_bt = QtWidgets.QPushButton(self.centralwidget)
        self.record_bt.setObjectName("record_bt")
        self.gridLayout.addWidget(self.record_bt, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 6, 1, 1)
        self.next_bt = QtWidgets.QPushButton(self.centralwidget)
        self.next_bt.setObjectName("next_bt")
        self.gridLayout.addWidget(self.next_bt, 0, 5, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 5, 0, 1, 3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setObjectName("image_label")
        self.gridLayout_5.addWidget(self.image_label, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 5, 2)
        self.count_label = QtWidgets.QLabel(self.centralwidget)
        self.count_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.count_label.setObjectName("count_label")
        self.gridLayout_4.addWidget(self.count_label, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pic1_label = QtWidgets.QLabel(self.centralwidget)
        self.pic1_label.setObjectName("pic1_label")
        self.verticalLayout.addWidget(self.pic1_label)
        self.pic3_label = QtWidgets.QLabel(self.centralwidget)
        self.pic3_label.setObjectName("pic3_label")
        self.verticalLayout.addWidget(self.pic3_label)
        self.pic5_label = QtWidgets.QLabel(self.centralwidget)
        self.pic5_label.setObjectName("pic5_label")
        self.verticalLayout.addWidget(self.pic5_label)
        self.pic7_label = QtWidgets.QLabel(self.centralwidget)
        self.pic7_label.setObjectName("pic7_label")
        self.verticalLayout.addWidget(self.pic7_label)
        self.pic9_label = QtWidgets.QLabel(self.centralwidget)
        self.pic9_label.setObjectName("pic9_label")
        self.verticalLayout.addWidget(self.pic9_label)
        self.back_bt = QtWidgets.QPushButton(self.centralwidget)
        self.back_bt.setObjectName("back_bt")
        self.verticalLayout.addWidget(self.back_bt)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pic2_label = QtWidgets.QLabel(self.centralwidget)
        self.pic2_label.setObjectName("pic2_label")
        self.verticalLayout_2.addWidget(self.pic2_label)
        self.pic4_label = QtWidgets.QLabel(self.centralwidget)
        self.pic4_label.setObjectName("pic4_label")
        self.verticalLayout_2.addWidget(self.pic4_label)
        self.pic6_label = QtWidgets.QLabel(self.centralwidget)
        self.pic6_label.setObjectName("pic6_label")
        self.verticalLayout_2.addWidget(self.pic6_label)
        self.pic8_label = QtWidgets.QLabel(self.centralwidget)
        self.pic8_label.setObjectName("pic8_label")
        self.verticalLayout_2.addWidget(self.pic8_label)
        self.pic10_label = QtWidgets.QLabel(self.centralwidget)
        self.pic10_label.setObjectName("pic10_label")
        self.verticalLayout_2.addWidget(self.pic10_label)
        self.forward_bt = QtWidgets.QPushButton(self.centralwidget)
        self.forward_bt.setObjectName("forward_bt")
        self.verticalLayout_2.addWidget(self.forward_bt)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 2, 4, 1)
        FaceWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FaceWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        FaceWindow.setMenuBar(self.menubar)
        self.new_act = QtWidgets.QAction(FaceWindow)
        self.new_act.setObjectName("new_act")
        self.open_act = QtWidgets.QAction(FaceWindow)
        self.open_act.setObjectName("open_act")
        self.save_act = QtWidgets.QAction(FaceWindow)
        self.save_act.setObjectName("save_act")
        self.exit_act = QtWidgets.QAction(FaceWindow)
        self.exit_act.setObjectName("exit_act")
        self.actionCommit = QtWidgets.QAction(FaceWindow)
        self.actionCommit.setObjectName("actionCommit")
        self.commit_act = QtWidgets.QAction(FaceWindow)
        self.commit_act.setObjectName("commit_act")
        self.menuFile.addAction(self.new_act)
        self.menuFile.addAction(self.open_act)
        self.menuFile.addAction(self.save_act)
        self.menuFile.addAction(self.commit_act)
        self.menuFile.addAction(self.exit_act)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(FaceWindow)
        QtCore.QMetaObject.connectSlotsByName(FaceWindow)

    def retranslateUi(self, FaceWindow):
        _translate = QtCore.QCoreApplication.translate
        FaceWindow.setWindowTitle(_translate("FaceWindow", "MainWindow"))
        self.previous_bt.setText(_translate("FaceWindow", "Previous"))
        self.record_bt.setText(_translate("FaceWindow", "Record"))
        self.next_bt.setText(_translate("FaceWindow", "Next"))
        self.image_label.setText(_translate("FaceWindow", "TextLabel"))
        self.count_label.setText(_translate("FaceWindow", "count"))
        self.pic1_label.setText(_translate("FaceWindow", "1"))
        self.pic3_label.setText(_translate("FaceWindow", "3"))
        self.pic5_label.setText(_translate("FaceWindow", "5"))
        self.pic7_label.setText(_translate("FaceWindow", "7"))
        self.pic9_label.setText(_translate("FaceWindow", "9"))
        self.back_bt.setText(_translate("FaceWindow", "Back"))
        self.pic2_label.setText(_translate("FaceWindow", "2"))
        self.pic4_label.setText(_translate("FaceWindow", "4"))
        self.pic6_label.setText(_translate("FaceWindow", "6"))
        self.pic8_label.setText(_translate("FaceWindow", "8"))
        self.pic10_label.setText(_translate("FaceWindow", "10"))
        self.forward_bt.setText(_translate("FaceWindow", "Forward"))
        self.menuFile.setTitle(_translate("FaceWindow", "File"))
        self.new_act.setText(_translate("FaceWindow", "New"))
        self.new_act.setShortcut(_translate("FaceWindow", "Ctrl+N"))
        self.open_act.setText(_translate("FaceWindow", "Open"))
        self.open_act.setShortcut(_translate("FaceWindow", "Ctrl+O"))
        self.save_act.setText(_translate("FaceWindow", "Save"))
        self.save_act.setShortcut(_translate("FaceWindow", "Ctrl+S"))
        self.exit_act.setText(_translate("FaceWindow", "Exit"))
        self.exit_act.setShortcut(_translate("FaceWindow", "Ctrl+Esc"))
        self.actionCommit.setText(_translate("FaceWindow", "Commit"))
        self.commit_act.setText(_translate("FaceWindow", "Commit"))
        self.commit_act.setShortcut(_translate("FaceWindow", "Ctrl+C"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     FaceWindow = QtWidgets.QMainWindow()
#     ui = Ui_FaceWindow()
#     ui.setupUi(FaceWindow)
#     FaceWindow.show()
#     sys.exit(app.exec_())
