# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_voiceWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoiceWindow(object):
    def setupUi(self, VoiceWindow):
        VoiceWindow.setObjectName("VoiceWindow")
        VoiceWindow.resize(800, 555)
        self.centralwidget = QtWidgets.QWidget(VoiceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.done_bt = QtWidgets.QPushButton(self.centralwidget)
        self.done_bt.setObjectName("done_bt")
        self.gridLayout_2.addWidget(self.done_bt, 0, 1, 1, 1)
        self.audioinput_lb = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.audioinput_lb.setFont(font)
        self.audioinput_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.audioinput_lb.setObjectName("audioinput_lb")
        self.gridLayout_2.addWidget(self.audioinput_lb, 0, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.record_bt = QtWidgets.QPushButton(self.centralwidget)
        self.record_bt.setObjectName("record_bt")
        self.horizontalLayout_4.addWidget(self.record_bt)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.status_lb = QtWidgets.QLabel(self.centralwidget)
        self.status_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.status_lb.setObjectName("status_lb")
        self.gridLayout.addWidget(self.status_lb, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.volume_sl = QtWidgets.QSlider(self.centralwidget)
        self.volume_sl.setOrientation(QtCore.Qt.Vertical)
        self.volume_sl.setObjectName("volume_sl")
        self.horizontalLayout_2.addWidget(self.volume_sl)
        self.volume_lb = QtWidgets.QLabel(self.centralwidget)
        self.volume_lb.setObjectName("volume_lb")
        self.horizontalLayout_2.addWidget(self.volume_lb)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.play_bt = QtWidgets.QPushButton(self.centralwidget)
        self.play_bt.setObjectName("play_bt")
        self.horizontalLayout_3.addWidget(self.play_bt)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 4, 1, 1)
        self.previous_bt = QtWidgets.QPushButton(self.centralwidget)
        self.previous_bt.setObjectName("previous_bt")
        self.gridLayout_2.addWidget(self.previous_bt, 0, 0, 1, 1)
        self.DeviceBox = QtWidgets.QComboBox(self.centralwidget)
        self.DeviceBox.setObjectName("DeviceBox")
        self.gridLayout_2.addWidget(self.DeviceBox, 0, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 1, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.record1_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.record1_cb.setObjectName("record1_cb")
        self.horizontalLayout.addWidget(self.record1_cb)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.record2_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.record2_cb.setObjectName("record2_cb")
        self.horizontalLayout.addWidget(self.record2_cb)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.record3_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.record3_cb.setObjectName("record3_cb")
        self.horizontalLayout.addWidget(self.record3_cb)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem14)
        self.record_sl = QtWidgets.QSlider(self.centralwidget)
        self.record_sl.setOrientation(QtCore.Qt.Horizontal)
        self.record_sl.setObjectName("record_sl")
        self.verticalLayout.addWidget(self.record_sl)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 2, 4)
        VoiceWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VoiceWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        VoiceWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VoiceWindow)
        self.statusbar.setObjectName("statusbar")
        VoiceWindow.setStatusBar(self.statusbar)
        self.new_act = QtWidgets.QAction(VoiceWindow)
        self.new_act.setObjectName("new_act")
        self.open_act = QtWidgets.QAction(VoiceWindow)
        self.open_act.setObjectName("open_act")
        self.save_act = QtWidgets.QAction(VoiceWindow)
        self.save_act.setObjectName("save_act")
        self.commit_act = QtWidgets.QAction(VoiceWindow)
        self.commit_act.setObjectName("commit_act")
        self.exit_act = QtWidgets.QAction(VoiceWindow)
        self.exit_act.setObjectName("exit_act")
        self.menuFile.addAction(self.new_act)
        self.menuFile.addAction(self.open_act)
        self.menuFile.addAction(self.save_act)
        self.menuFile.addAction(self.commit_act)
        self.menuFile.addAction(self.exit_act)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(VoiceWindow)
        QtCore.QMetaObject.connectSlotsByName(VoiceWindow)

    def retranslateUi(self, VoiceWindow):
        _translate = QtCore.QCoreApplication.translate
        VoiceWindow.setWindowTitle(_translate("VoiceWindow", "MainWindow"))
        self.done_bt.setText(_translate("VoiceWindow", "Done"))
        self.audioinput_lb.setText(_translate("VoiceWindow", "Audio input:"))
        self.record_bt.setText(_translate("VoiceWindow", "Record"))
        self.status_lb.setText(_translate("VoiceWindow", "Status: Click record"))
        self.volume_lb.setText(_translate("VoiceWindow", "Volume"))
        self.play_bt.setText(_translate("VoiceWindow", "Play"))
        self.previous_bt.setText(_translate("VoiceWindow", "Previous"))
        self.record1_cb.setText(_translate("VoiceWindow", "Record 1"))
        self.record2_cb.setText(_translate("VoiceWindow", "Record 2"))
        self.record3_cb.setText(_translate("VoiceWindow", "Record 3"))
        self.menuFile.setTitle(_translate("VoiceWindow", "File"))
        self.new_act.setText(_translate("VoiceWindow", "New"))
        self.new_act.setShortcut(_translate("VoiceWindow", "Ctrl+N"))
        self.open_act.setText(_translate("VoiceWindow", "Open"))
        self.open_act.setShortcut(_translate("VoiceWindow", "Ctrl+O"))
        self.save_act.setText(_translate("VoiceWindow", "Save"))
        self.save_act.setShortcut(_translate("VoiceWindow", "Ctrl+S"))
        self.commit_act.setText(_translate("VoiceWindow", "Commit"))
        self.commit_act.setShortcut(_translate("VoiceWindow", "Ctrl+C"))
        self.exit_act.setText(_translate("VoiceWindow", "Exit"))
        self.exit_act.setShortcut(_translate("VoiceWindow", "Ctrl+Esc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoiceWindow = QtWidgets.QMainWindow()
    ui = Ui_VoiceWindow()
    ui.setupUi(VoiceWindow)
    VoiceWindow.show()
    sys.exit(app.exec_())
