# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Jetson.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.image_label = QtWidgets.QLabel(self.groupBox)
        self.image_label.setGeometry(QtCore.QRect(0, 0, 1011, 581))
        self.image_label.setAutoFillBackground(True)
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.info_label = QtWidgets.QLabel(self.groupBox)
        self.info_label.setGeometry(QtCore.QRect(40, 130, 251, 241))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.info_label.setFont(font)
        self.info_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_label.setAutoFillBackground(False)
        self.info_label.setStyleSheet("font: 57 25pt \"Ubuntu\";\n"
"font-weight: bold;\n"
"color: rgb(84, 0, 0);\n"
"background-color : rgba(255, 255, 255, 90);")
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.face_label = QtWidgets.QLabel(self.groupBox)
        self.face_label.setGeometry(QtCore.QRect(250, 50, 521, 501))
        self.face_label.setText("")
        self.face_label.setPixmap(QtGui.QPixmap("UI/face.png"))
        self.face_label.setScaledContents(True)
        self.face_label.setObjectName("face_label")
        self.yes_button = QtWidgets.QPushButton(self.groupBox)
        self.yes_button.setGeometry(QtCore.QRect(790, 360, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.yes_button.setFont(font)
        self.yes_button.setStyleSheet("background-color: rgb(252, 233, 79);\n"
"selection-background-color: rgb(143, 89, 2);")
        self.yes_button.setObjectName("yes_button")
        self.no_button = QtWidgets.QPushButton(self.groupBox)
        self.no_button.setGeometry(QtCore.QRect(790, 430, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.no_button.setFont(font)
        self.no_button.setStyleSheet("background-color: rgb(252, 233, 79);\n"
"selection-background-color: rgb(143, 89, 2);")
        self.no_button.setObjectName("no_button")
        self.checked_label = QtWidgets.QLabel(self.groupBox)
        self.checked_label.setGeometry(QtCore.QRect(760, 20, 211, 288))
        self.checked_label.setText("")
        self.checked_label.setObjectName("checked_label")
        self.device_label = QtWidgets.QLabel(self.groupBox)
        self.device_label.setGeometry(QtCore.QRect(40, 480, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.device_label.setFont(font)
        self.device_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.device_label.setAutoFillBackground(False)
        self.device_label.setStyleSheet("font: 57 25pt \"Ubuntu\";\n"
"font-weight: bold;\n"
"color: rgb(84, 0, 0);\n"
"background-color : rgba(255, 255, 255, 90);")
        self.device_label.setText("")
        self.device_label.setAlignment(QtCore.Qt.AlignCenter)
        self.device_label.setObjectName("device_label")
        self.course_label = QtWidgets.QLabel(self.groupBox)
        self.course_label.setGeometry(QtCore.QRect(40, 370, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.course_label.setFont(font)
        self.course_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.course_label.setAutoFillBackground(False)
        self.course_label.setStyleSheet("font: 57 25pt \"Ubuntu\";\n"
"font-weight: bold;\n"
"color: rgb(84, 0, 0);\n"
"background-color : rgba(255, 255, 255, 90);")
        self.course_label.setText("")
        self.course_label.setAlignment(QtCore.Qt.AlignCenter)
        self.course_label.setObjectName("course_label")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.yes_button.setText(_translate("MainWindow", "YES"))
        self.no_button.setText(_translate("MainWindow", "NO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
